import type { Listing, Project } from '@/types/marketplace';
import type { BlogPostDetail } from '@/lib/wordpress/types';
import { createMetadata } from './metadata';

export const readableSlug = (value: string) => value.split('-').map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(' ');
export const generateHomeMetadata = () => createMetadata({ title: 'Properties for Sale and Rent in Pakistan', description: 'Discover verified houses, plots, apartments, commercial property and transparent new projects across Pakistan.', path: '/' });
export const generateCityMetadata = (purpose: 'sale' | 'rent' | 'projects', city: string) => createMetadata({ title: purpose === 'sale' ? `Properties for Sale in ${city}` : purpose === 'rent' ? `Properties for Rent in ${city}` : `New Projects in ${city}`, description: purpose === 'sale' ? `Browse houses, plots, apartments and commercial properties for sale in ${city} with verification signals and direct inquiries.` : purpose === 'rent' ? `Find houses and apartments for rent in ${city} with fresh listings and safer inquiry options.` : `Explore new real-estate projects in ${city} with developer, possession and payment-plan details.`, path: purpose === 'sale' ? `/buy/${city.toLowerCase().replace(/\s+/g, '-')}` : purpose === 'rent' ? `/rent/${city.toLowerCase().replace(/\s+/g, '-')}` : `/projects/${city.toLowerCase().replace(/\s+/g, '-')}` });
export const generatePropertyTypeMetadata = (propertyType: string, city?: string, purpose: 'sale' | 'rent' = 'sale', code?: string, citySlug?: string) => createMetadata({ title: `${propertyType}${purpose === 'sale' ? ' for Sale' : ' for Rent'}${city ? ` in ${city}` : ' in Pakistan'}`, description: `Browse ${propertyType.toLowerCase()} ${purpose === 'sale' ? 'for sale' : 'for rent'}${city ? ` in ${city}` : ' across Pakistan'} with verified signals and direct inquiries.`, path: purpose === 'sale' ? citySlug && code ? `/buy/${code}/${citySlug}` : `/buy/${code ?? propertyType.toLowerCase()}` : `/rent/${citySlug ?? ''}` });
export const generateAreaMetadata = (area: string, city: string, slug: string) => createMetadata({ title: `Property in ${area}, ${city}`, description: `Explore properties for sale and rent, nearby projects and practical guides for ${area}, ${city}.`, path: `/area/${slug}` });
export const generateListingMetadata = (listing: Listing) => createMetadata({ title: `${listing.title} | ${listing.areaName}, ${listing.cityName}`, description: `${listing.title} in ${listing.areaName}, ${listing.cityName}. View property details, price, photos, verification signals and inquiry options.`, path: `/listing/${listing.publicId}`, image: listing.coverImageUrl });
export const generateProjectMetadata = (project: Project) => createMetadata({ title: `${project.name} | ${project.cityName}`, description: `${project.name} by ${project.developerName} in ${project.areaName}, ${project.cityName}. Review units, possession, payment plan and project updates.`, path: `/project/${project.slug}`, image: project.coverImageUrl });
export const generateBlogMetadata = (post: BlogPostDetail) => createMetadata({ title: post.title, description: post.excerpt ?? `Read ${post.title} on Gharazi.`, path: `/blog/${post.slug}`, image: post.coverImageUrl, type: 'article' });
export const generateAdvertiseMetadata = () => createMetadata({ title: 'Advertise Property and Real Estate Projects', description: 'Promote listings, agencies, developers and real-estate projects with Gharazi advertising packages.', path: '/advertise' });
export const generateProfessionalMetadata = (name: string, slug: string, type: 'agency' | 'developer' = 'agency') => createMetadata({ title: `${name} | ${type === 'developer' ? 'Developer' : 'Real Estate Agency'}`, description: `View ${name} profile, active property inventory and verification information on Gharazi.`, path: `/${type}/${slug}` });
