import type { Listing, Project } from '@/types/marketplace';
import type { BlogPostDetail } from '@/lib/wordpress/types';
import { absoluteUrl } from './canonical';

export type BreadcrumbDataItem = { label: string; href?: string };
export const breadcrumbSchema = (items: BreadcrumbDataItem[]) => ({ '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: items.map((item, index) => ({ '@type': 'ListItem', position: index + 1, name: item.label, item: item.href ? absoluteUrl(item.href) : undefined })) });
export const homeSchemas = () => [{ '@context': 'https://schema.org', '@type': 'WebSite', name: 'Gharazi', url: absoluteUrl('/'), potentialAction: { '@type': 'SearchAction', target: `${absoluteUrl('/buy')}?q={search_term_string}`, 'query-input': 'required name=search_term_string' } }, { '@context': 'https://schema.org', '@type': 'Organization', name: 'Gharazi', url: absoluteUrl('/'), logo: absoluteUrl('/icon.png') }];
export const listingSchemas = (listing: Listing) => [{ '@context': 'https://schema.org', '@type': 'RealEstateListing', name: listing.title, description: listing.description, url: absoluteUrl(`/listing/${listing.publicId}`), datePosted: listing.publishedAt, image: listing.images?.map((image) => ({ '@type': 'ImageObject', contentUrl: image.url, caption: image.alt ?? listing.title })), offers: { '@type': 'Offer', price: listing.priceAmount, priceCurrency: 'PKR', availability: 'https://schema.org/InStock' }, contentLocation: { '@type': 'Place', name: `${listing.areaName}, ${listing.cityName}`, address: { '@type': 'PostalAddress', addressLocality: listing.areaName, addressRegion: listing.cityName, addressCountry: 'PK' } }, about: { '@type': 'Residence', name: listing.title, numberOfBedrooms: listing.bedrooms, numberOfBathroomsTotal: listing.bathrooms, floorSize: listing.areaValue ? { '@type': 'QuantitativeValue', value: listing.areaValue, unitText: listing.areaUnit } : undefined } }];
export const projectSchemas = (project: Project) => [{ '@context': 'https://schema.org', '@type': 'Residence', name: project.name, description: project.description, url: absoluteUrl(`/project/${project.slug}`), image: project.coverImageUrl ? { '@type': 'ImageObject', contentUrl: project.coverImageUrl, caption: project.name } : undefined, containedInPlace: { '@type': 'Place', name: `${project.areaName}, ${project.cityName}`, address: { '@type': 'PostalAddress', addressLocality: project.areaName, addressRegion: project.cityName, addressCountry: 'PK' } }, offers: project.minPriceAmount ? { '@type': 'Offer', price: project.minPriceAmount, priceCurrency: 'PKR' } : undefined, provider: { '@type': 'Organization', name: project.developerName } }];
export const blogSchemas = (post: BlogPostDetail) => [{ '@context': 'https://schema.org', '@type': ['Article', 'BlogPosting'], headline: post.title, description: post.excerpt, image: post.coverImageUrl ? { '@type': 'ImageObject', contentUrl: post.coverImageUrl, caption: post.coverImageAlt ?? post.title } : undefined, datePublished: post.publishedAt, mainEntityOfPage: absoluteUrl(`/blog/${post.slug}`), author: { '@type': 'Person', name: post.authorName ?? 'Gharazi Editorial' }, publisher: { '@type': 'Organization', name: 'Gharazi', url: absoluteUrl('/') } }];
export const faqSchema = (items: Array<[string, string]>) => ({ '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: items.map(([question, answer]) => ({ '@type': 'Question', name: question, acceptedAnswer: { '@type': 'Answer', text: answer } })) });
