'use client';

import { useMutation, useQueryClient } from '@tanstack/react-query';
import Link from 'next/link';
import { Badge, InfoChip } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { EmptyState, ErrorState, Skeleton } from '@/components/ui/state';
import { requestProfessionalVerification } from '@/lib/api/professional';
import { useProfessionalSummary } from '@/lib/query/hooks';
import { formatDate } from '@/lib/utils';

export function ProfessionalDashboardClient() {
  const query = useProfessionalSummary(); const queryClient = useQueryClient();
  const verify = useMutation({ mutationFn: requestProfessionalVerification, onSuccess: () => queryClient.invalidateQueries({ queryKey: ['professional-summary'] }) });
  if (query.isLoading) return <Skeleton className="h-96" />;
  if (query.isError || !query.data) return <ErrorState title="Professional dashboard unavailable" message="Please retry. Your existing dashboard and inventory are unaffected." />;
  const data = query.data;
  if (!data.eligible && !data.profile) return <Card className="p-8"><EmptyState title="Create a Company / Professional profile" message="Set up a business identity to access professional inventory, lead, package, and performance tools." /><div className="mt-5 flex justify-center gap-3"><Button asChild href="/dashboard/professional/setup">Create professional profile</Button><Button asChild href="/help" variant="secondary">Learn more</Button></div></Card>;
  if (!data.profile) return <Card className="p-8"><EmptyState title="Finish your business setup" message="Your account role is eligible for professional tools. Create the business profile to complete onboarding." /><Button className="mt-5" asChild href="/dashboard/professional/setup">Start setup</Button></Card>;
  const subscriptionName = data.subscription?.plan?.name ?? data.subscription?.packageCode ?? 'Free / Basic';
  return <div className="grid gap-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold text-trust">Company / Professional</p><h1 className="text-3xl font-black">{data.profile.businessName}</h1><p className="mt-1 text-muted">Your private business performance and action center.</p></div><div className="flex gap-2"><Button asChild href="/dashboard/professional/profile" variant="secondary">Edit profile</Button><Button asChild href="/dashboard/listings/new">Add listing</Button></div></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[['Active listings', data.counts.activeListings], ['Active projects', data.counts.activeProjects], ['Views this month', data.metrics.viewsThisMonth], ['New inquiries', data.metrics.inquiriesThisMonth], ['Messages', data.metrics.messagesThisMonth], ['Favorites', data.metrics.favoritesThisMonth], ['Unread chats', data.counts.unreadChats], ['Profile complete', `${data.profileCompletion}%`]].map(([label, value]) => <Card key={String(label)} className="p-5"><p className="text-sm font-semibold text-muted">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></Card>)}</div>
    <div className="grid gap-4 lg:grid-cols-3">
      <Card className="p-5"><div className="flex justify-between"><h2 className="text-lg font-black">Business verification</h2><Badge>{data.verificationStatus}</Badge></div><p className="mt-3 text-sm text-muted">Verification helps customers identify reviewed professional businesses. Keep your identity and contact information complete.</p>{data.profile.rejectionReason ? <p className="mt-3 text-sm text-red-700">Reason: {data.profile.rejectionReason}</p> : null}{['unverified', 'rejected'].includes(data.verificationStatus) ? <Button className="mt-4" disabled={verify.isPending} onClick={() => verify.mutate()}>Request verification</Button> : null}{verify.isError ? <p className="mt-2 text-sm text-red-700">{verify.error.message}</p> : null}</Card>
      <Card className="p-5"><h2 className="text-lg font-black">Package</h2><p className="mt-3 text-2xl font-black text-trust">{subscriptionName}</p><p className="mt-1 text-sm text-muted">Status: {data.subscription?.status ?? 'free'}</p>{data.subscription?.currentPeriodEnd || data.subscription?.endAt ? <p className="mt-1 text-sm text-muted">Renews/ends {formatDate(data.subscription.currentPeriodEnd ?? data.subscription.endAt)}</p> : null}<Button className="mt-4" asChild href="/advertise" variant="secondary">Upgrade visibility</Button></Card>
      <Card className="p-5"><h2 className="text-lg font-black">Informational quota</h2><p className="mt-3 text-sm">Listings: {data.quota.activeListingsUsed} / {data.quota.activeListingLimit}</p><p className="mt-2 text-sm">Projects: {data.quota.activeProjectsUsed} / {data.quota.activeProjectLimit}</p><p className="mt-3 text-xs text-muted">Limits are display-only in this release.</p>{data.quota.canCreateProject ? <Button className="mt-4" asChild href="/dashboard/projects/new" variant="secondary">Add project</Button> : null}</Card>
    </div>
    <div className="grid gap-4 lg:grid-cols-2"><ListCard title="Recent listings" empty="No listings yet." href="/dashboard/listings" items={data.recentListings.map((item) => ({ id: item.id, title: item.title, meta: `${item.status} · ${item.viewCount ?? 0} views · ${item.inquiryCount ?? 0} inquiries`, href: `/listing/${item.publicId}` }))} /><ListCard title="Recent projects" empty="No projects yet." href="/dashboard/projects" items={data.recentProjects.map((item) => ({ id: item.id, title: item.name, meta: item.status, href: `/project/${item.slug}` }))} /></div>
    <div className="grid gap-4 lg:grid-cols-2"><ListCard title="Recent leads" empty="No inquiries received yet." href="/dashboard/inquiries" items={data.recentLeads.map((item) => ({ id: item.id, title: item.listing?.title ?? item.project?.name ?? 'Inquiry', meta: `${item.status} · ${formatDate(item.createdAt)}`, href: `/dashboard/inquiries?${item.listing?.id ? `listingId=${item.listing.id}` : `projectId=${item.project?.id}`}` }))} /><ListCard title="Active promotions" empty="No active promotions." href="/advertise" items={data.promotedItems.map((item) => ({ id: item.id, title: item.packageCode ?? item.promotionType, meta: `${item.status} · ends ${formatDate(item.endsAt)}`, href: item.entityType === 'listing' ? '/dashboard/listings' : '/dashboard/projects' }))} /></div>
    <Card className="p-5"><h2 className="text-lg font-black">Quick actions</h2><div className="mt-4 flex flex-wrap gap-2"><Button asChild href="/dashboard/listings/new">Add listing</Button><Button asChild href="/dashboard/inquiries" variant="secondary">View leads</Button><Button asChild href="/dashboard/chats" variant="secondary">Open chats</Button><Button asChild href="/advertise" variant="secondary">Promote inventory</Button></div></Card>
  </div>;
}

function ListCard({ title, empty, href, items }: { title: string; empty: string; href: string; items: Array<{ id: string; title: string; meta: string; href: string }> }) { return <Card className="p-5"><div className="flex justify-between"><h2 className="text-lg font-black">{title}</h2><Link className="text-sm font-bold text-trust" href={href}>View all</Link></div><div className="mt-4 grid gap-2">{items.length ? items.map((item) => <Link key={item.id} href={item.href} className="rounded-md border border-line p-3"><p className="font-semibold">{item.title}</p><p className="mt-1 text-xs text-muted">{item.meta}</p></Link>) : <p className="text-sm text-muted">{empty}</p>}</div></Card>; }
